# base on https://github.com/blogimg/WakeLeanCloud
name: wake

on: 
  push:
    branches:
      - backup
    paths:
      - '.github/workflows/wake.yml'
  schedule:
    - cron: "*/18 0-15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: backup

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requests
      run: pip install requests

    - name: Waking
      run:  python wake.py